title   = 'iNetech Blog'
baseURL = 'https://blog.inetech.fun/'

hasCJKLanguage = true
languageCode   = 'zh-cmn-Hans'
DefaultContentLanguage = "zh"

theme = 'diary'

paginate = 7
uglyURLs = false
enableEmoji = true
enableRobotsTXT = true

[params]
subtitle = "感时花溅泪，恨别鸟惊心。"

[[menu.main]]
url = "/posts"
name = "归档"
weight = 1

[[menu.main]]
url = "/categories"
name = "分类"
weight = 2

[[menu.main]]
url = "/tags"
name = "标签"
weight = 3

[[menu.main]]
url = "/links"
name = "友链"
weight = 4

[[menu.main]]
url = "/privacy"
name = "隐私"
weight = 5

[[menu.main]]
url = "/thanks"
name = "致谢"
weight = 6

[[menu.main]]
url = "/about"
name = "关于"
weight = 7

[[menu.main]]
url = "/index.xml"
name = "订阅"
weight = 8

[markup]
  [markup.highlight]
    lineNumbersInTable = false
    guessSyntax = true
    lineNos = true
    style = 'nord'
    tabWidth = 2
